### ISSUE TITLE
Search bar closing on setState call

### ISSUE THREAD

**Issue by lbottona** [blackshadowsoftwareltd/animation_search_bar#1]
Hi! I'm using this package as searchBar for my project. I'm using the function setState in onChange to adapt dynamically my list, but, doing like this, every time I type a character, the search is closing. I'll paste the cose down below. 

> `PreferredSizeWidget? AppbarFriendSearch(){

    return PreferredSize(
        preferredSize: const Size(double.infinity, 65),
        child: SafeArea(
            child: Container(
              alignment: Alignment.center,
              child: AnimationSearchBar(
                  backIconColor: Colors.black,
                  centerTitle: 'Friends',
                  centerTitleStyle: TextStyle(color: Theme.of(context).colorScheme.secondary, fontSize: 20),
                  onChanged: (text) {
                    if(text.isEmpty){
                      setState((){
                        _subListFriends = _friends;
                      });
                    }else{
                      setState(() {
                        _subListFriends = _friends
                            .where((b) => b.username.toString().toLowerCase().contains(text.toLowerCase()))
                            .toList();
                      });
                    }
                  },
                  searchTextEditingController: controller,
                  horizontalPadding: 5,
                  isBackButtonVisible: false,
              ),
            )
        )
    );
  }`

**Comment by RemonAhammad** [comment]
We have fixed setState issue, Please check it out. follow on example.
